name: First Workflow # workflow name
on: push # which will trigger
jobs:
  first-job: # job name
    #the runner env
    runs-on: ubuntu-latest
    steps:
      - name: show state # step name
        run: top
      - name: show ip
        run: ifconfig
        
