name: First Workflow # workflow name
on: push # which will trigger
jobs:
  first-job: # job name
    #the runner env
    runs-on: ubuntu-latest
    steps:
      - name: ip install # step name
        run: sudo apt install net-tools
      - name: show ip
        run: ifconfig
        
