name: First Workflow # workflow name
on: push # which will trigger
jobs:
  first-job: # job name
    #the runner env
    runs-on: ubuntu-latest
    steps:
      - name: run react # step name
        run: npx create-react-app my-app
      - name: cd to directory
        run: cd my-app
      - name: start react
        run: npm start
        
